### ISSUE TITLE
📦 Enable Docker buildx cache in CI for faster container builds

### ISSUE THREAD

**Issue by JohnBasrai** [JohnBasrai/rust-dev-tools#8]
### 📝 **Description**

Currently, the `rust-base-containers` CI workflow does not enable caching for Docker `buildx`, resulting in slower builds for every commit — even when layers haven't changed.

We’ve already implemented a successful caching strategy in the `cr8s` repo using `actions/cache@v4`:

```yaml
- name: 🚧 Set up Docker Buildx
  uses: docker/setup-buildx-action@v3
  with:
    install: true
    driver-opts: image=moby/buildkit:latest
    buildkitd-flags: --debug
    driver: docker-container
    name: cr8s-builder
    use: true

- name: 📁 Setup Docker buildx cache
  uses: actions/cache@v4
  with:
    path: /tmp/.buildx-cache
    key: ${{ runner.os }}-buildx-${{ github.sha }}
    restore-keys: |
      ${{ runner.os }}-buildx-
```

---

### 🎯 **Solution**

Update the CI workflow (`ci.yml`) in `rust-base-containers` to:

1. Set up a persistent Docker layer cache with `actions/cache@v4`
2. Point `buildx` to use `/tmp/.buildx-cache` for both read/write
3. Validate that subsequent PRs reuse cached intermediate layers for faster CI times

> 🧠 Note: This cache only persists between jobs on the same branch or across recent commits — it is not a build artifact, but a filesystem-level reuse layer.

---

### 🧪 Bonus

* Speeds up workflows where `Cargo.toml` and base image layers haven't changed
* Particularly useful when only Dockerfile logic changes or small Rust crate edits occur

---

### 📋 **Metadata**

```markdown
| Field        | Value                            |
|--------------|----------------------------------|
| Status       | Ready                            |
| Type         | Task                             |
| Area         | CI / GitHub Actions              |
| Priority     | Low-Medium                       |
| Upstream     | rust-base-containers             |
| Blocked By   | N/A                              |
| Branch       | TBD                              |
```
